<?xml version="1.0" standalone="yes"?>
<!-- This file has been generated by DOcplex version 2.25.236  -->
<CPLEXSolution version="1.0">
    <header problemName="example" objectiveValue="0" />
    <variables>
        <variable name="x[1][1]" value="0" />
        <variable name="x[1][2]" value="1" />
        <variable name="x[1][3]" value="1" />
        <variable name="x[1][4]" value="0" />
        <variable name="x[1][5]" value="0" />
        <variable name="x[1][6]" value="0" />
        <variable name="x[1][7]" value="1" />
        <variable name="x[2][1]" value="0" />
        <variable name="x[2][2]" value="0" />
        <variable name="x[2][3]" value="1" />
        <variable name="x[2][4]" value="1" />
        <variable name="x[2][5]" value="0" />
        <variable name="x[2][6]" value="0" />
        <variable name="x[2][7]" value="0" />
    </variables>
</CPLEXSolution>
